services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baitap1-jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    working_dir: /home/jovyan/work